FROM profuzz-mbedtls-cert

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up AFL-ML
ENV AFLML="/home/ubuntu/aflml"

RUN git clone https://github.com/remiparrot/aflnet $AFLML && \
    cd $AFLML && \
    make clean all $MAKE_OPT && \
    cd llvm_mode && make $MAKE_OPT

# Set up environment variables for AFL-ML
ENV AFL_PATH=${AFLML}
ENV PATH=${AFLML}:${PATH}

# Dedicated instrumented version for AFL-ML
RUN cd $WORKDIR && \
    git clone https://github.com/Mbed-TLS/mbedtls mbedtls-aflml && \
    cd mbedtls-aflml && \
		git checkout c2f5b08 && \
		./scripts/config.py set MBEDTLS_PLATFORM_TIME_ALT && \
    AFL_USE_ASAN=1 CC=${AFLML}/afl-clang-fast make $MAKE_OPT

COPY --chown=ubuntu:ubuntu cert/in-dtls-aflml ${WORKDIR}/in-dtls-aflml
COPY --chown=ubuntu:ubuntu run-aflml.sh ${WORKDIR}/run-aflml

