FROM profuzz-wolfssl

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up AFL-ML
ENV AFLML="/home/ubuntu/aflml"

RUN git clone https://github.com/remiparrot/aflnet $AFLML && \
    cd $AFLML && \
    make clean all $MAKE_OPT && \
    cd llvm_mode && make $MAKE_OPT

# Set up environment variables for AFL-ML
ENV AFL_PATH=${AFLML}
ENV PATH=${AFLML}:${PATH}

# Dedicated instrumented version for AFL-ML
RUN cd $WORKDIR && \
    git clone https://github.com/wolfSSL/wolfssl wolfssl-aflml && \
    cd wolfssl-aflml && \
		git checkout 870f7cc && \
    patch -p1 < $WORKDIR/determ.patch && \
		./autogen.sh && \
		AFL_USE_ASAN=1 CC=afl-clang-fast AM_CFLAGS='-DHAVE_AES_CBC -DWOLFSSL_AES_128' ./configure  --enable-dtls --enable-psk --enable-rsa --enable-sha --enable-debug --disable-dh --disable-ecc --enable-static C_EXTRA_FLAGS=-DWOLFSSL_STATIC_PSK && \
    AFL_USE_ASAN=1 CC=afl-clang-fast make $MAKE_OPT

COPY --chown=ubuntu:ubuntu in-dtls-aflml ${WORKDIR}/in-dtls-aflml
COPY --chown=ubuntu:ubuntu run-aflml.sh ${WORKDIR}/run-aflml

