FROM profuzz-openssl-3.0-cert

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up AFL-ML
ENV AFLML="/home/ubuntu/aflml"

RUN git clone https://github.com/remiparrot/aflnet $AFLML && \
    cd $AFLML && \
    make clean all $MAKE_OPT && \
    cd llvm_mode && make $MAKE_OPT

# Set up environment variables for AFL-ML
ENV AFL_PATH=${AFLML}
ENV PATH=${AFLML}:${PATH}

# Dedicated instrumented version for AFL-ML
RUN cd $WORKDIR && \
    git clone https://github.com/openssl/openssl.git openssl-aflml && \
    cd openssl-aflml && \
		git checkout 39ed41b && \
    patch -p1 < $WORKDIR/determ.patch && \
		AFL_USE_ASAN=1 CC=afl-clang-fast ./config enable-asan enable-fuzz-afl no-shared no-module -DPEDANTIC enable-tls1_3 enable-weak-ssl-ciphers enable-rc5 enable-md2 enable-ssl3 enable-ssl3-method enable-nextprotoneg enable-ec_nistp_64_gcc_128 -fno-sanitize=alignment --debug && \
    AFL_USE_ASAN=1 CC=afl-clang-fast make $MAKE_OPT

COPY --chown=ubuntu:ubuntu cert/in-dtls-aflml ${WORKDIR}/in-dtls-aflml
COPY --chown=ubuntu:ubuntu run-aflml.sh ${WORKDIR}/run-aflml

