FROM profuzz-etinydtls-5e14e49

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up AFL-ML
ENV AFLML="/home/ubuntu/aflml"

RUN git clone https://github.com/remiparrot/aflnet $AFLML && \
    cd $AFLML && \
    make clean all $MAKE_OPT && \
    cd llvm_mode && make $MAKE_OPT

# Set up environment variables for AFL-ML
ENV AFL_PATH=${AFLML}
ENV PATH=${AFLML}:${PATH}

# Dedicated instrumented version for AFL-ML
RUN cd $WORKDIR && \
    git clone  https://github.com/eclipse/tinydtls tinydtls-aflml && \
    cd tinydtls-aflml && \
    git checkout de74a02 && \
    patch -p1 < $WORKDIR/fuzzing.patch && \
		./autogen.sh && \
		CC=${AFLML}/afl-clang-fast ./configure && \
    make clean && \
    CC=${AFLML}/afl-clang-fast make $MAKE_OPT

COPY --chown=ubuntu:ubuntu in-dtls-aflml ${WORKDIR}/in-dtls-aflml
COPY --chown=ubuntu:ubuntu run-aflml.sh ${WORKDIR}/run-aflml

